version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "20m"

services:

  db:
    container_name: z_db
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: z
      MYSQL_PASSWORD: root
    # volumes:
      # - ./docker/mariadb/config:/etc/mysql/conf.d:ro
      # - ./db/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    depends_on:
      - db
    ports:
      - 8081:80

  #### For Laravel
  php:
    container_name: z-php
    build:
      context: .
      dockerfile: ./docker/laravel-php/Dockerfile
    volumes:
      - ./web:/var/www
      - ./docker/laravel-php/php.ini:/usr/local/etc/php/php.ini
      # - data-volume:/var/lib/share
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: z-nginx
    ports:
      - 80:80
    volumes:
      - ./web:/var/www
      - ./docker/laravel-nginx/dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    links:
      - php
